name: Build LaTeX document
on: [push]
permissions: write-all
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ./cv.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: cv.pdf
          path: ./cv.pdf
          compression-level: 0
      - name: commit and push changes
        run: |
          git config --global user.name 'Joshua Murray'
          git config --global user.email 'joshmurray-geo@users.noreply.github.com'
          git add -A
          if ! git diff-index --quiet HEAD; then
            git commit -m "Automated build $GIT_COMMIT"
            git push origin $DEPLOY_BRANCH
          fi
